node {
  def remote = [:]
  remote.name = 'ansible-container'
  remote.host = '172.18.0.2'
  remote.user = 'root'
  remote.password = 'welcome@1234'
  remote.allowAnyHosts = true
  //def rowsCommand = ''
  stage('Lun Path Inputs'){
    script{
        lunIdPSCommand = sh(script: 'ansible-playbook -i playbooks/inventory playbooks/main.yml -vvv', returnStdout: true)
       println lunIdPSCommand
    }
  }
  stage('Remote SSH') {
           //sh 'ansible --version'
           //sh 'ansible-playbook -i playbooks/inventory playbooks/main.yml -vvv'
           sshCommand remote: remote, command:lunIdPSCommand
  }
}
