pipeline {
    agent any
    stages {
        stage('Github-Integration') {
            steps {
                 sh 'pwd; ansible-playbook -i playbooks/inventory playbooks/main.yml  -vvv'
            }
        }
    
    }
   
}
